// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzieEm8g0862FB0bNQM5uo6lXSmEAUwbY',
    appId: '1:56405015770:web:11498182dbc385b3b3f9e3',
    messagingSenderId: '56405015770',
    projectId: 'chatroute-fed9f',
    authDomain: 'chatroute-fed9f.firebaseapp.com',
    storageBucket: 'chatroute-fed9f.appspot.com',
    measurementId: 'G-37MM9W5FK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMkjLR2IgEcJtZQTMcW6ClSJUqdFNJ87c',
    appId: '1:56405015770:android:583cc48e79b7c660b3f9e3',
    messagingSenderId: '56405015770',
    projectId: 'chatroute-fed9f',
    storageBucket: 'chatroute-fed9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8727LNIxLYQKpKecEvrqyLu409I8UfDc',
    appId: '1:56405015770:ios:a12ea5b9c4edd881b3f9e3',
    messagingSenderId: '56405015770',
    projectId: 'chatroute-fed9f',
    storageBucket: 'chatroute-fed9f.appspot.com',
    iosBundleId: 'com.example.chatRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8727LNIxLYQKpKecEvrqyLu409I8UfDc',
    appId: '1:56405015770:ios:6314fde4b971578eb3f9e3',
    messagingSenderId: '56405015770',
    projectId: 'chatroute-fed9f',
    storageBucket: 'chatroute-fed9f.appspot.com',
    iosBundleId: 'com.example.chatRoute.RunnerTests',
  );
}
